name: dmap
description: Library to map Map<String, dynamic> into Class
version: 0.2.0
homepage: https://github.com/platelk/dmap
author: PLATEL Kevin <platel.kevin@gmail.con>

environment:
  sdk: '>=2.1.0 <3.0.0'

dev_dependencies:
  pedantic: ^1.0.0
  test: ^1.5.3
